# Site settings
title: Amber Dallas
email: amberdallas70@gmail.com
url: "https://github.com/amberdallas-portfolio"
baseurl: "/cyber-portfolio"
description: "Portfolio of cybersecurity work samples for a junior-level cyber security professional."
keywords: "cybersecurity, cyber, security, portfolio, tech"
skills: "Cybersecurity - Analyst - Ethical Hacker"
meta_author: Amber Dallas

# Contact form
contact: static

# Color settings
color:
  primary: BDE0FE
  primary-rgb: "45,215,185"
  secondary: FFAFCC
  secondary-dark: CDB4DB

# Footer settings
footer:
  copyright: Amber Dallas
  location: Location
  social: Around the Web
  credits: Credits

# Social networks
social:
  - title: linkedin
    url: https://www.linkedin.com/in/amber-dallas/
  - title: github
    url: https://github.com/amberdallas-portfolio

# Email link
contact_email: "mailto:amberdallas70@gmail.com"
